name: Lint

on: push

jobs:
 linter:
  runs-on: unbuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: install eslint
    run: npm install --save-dev eslint
  - name: run eslint
    run: npx eslint *.js
 
